### PR TITLE
New VZ cli repository

### PR DESCRIPTION
**Pull request by michaelfarrell76**
Sets up barebones for cli repo:

- pre commits
- yarn
- github deployment
- eslint
- typescript
- 1 cli command for `vz-combine-legal-csv`

### CODE REVIEW

**Review by giacaglia — APPROVED** [review]
Can't you gitignore the cache?

**Comment by michaelfarrell76** [comment]
@giacaglia we could - but in some repos we add it because it speeds things up

**Comment by giacaglia** [comment]
Got it!

**Comment by michaelfarrell76** [comment]
@dmattia @giacaglia could i get an approval?

**Review by giacaglia — APPROVED** [review]

**Pull request merged**
